copy kszla_header.ini rki_header.ini /Y
copy kszla_header.ini rbe_header.ini /Y
copy kszla_header.ini lelt_header.ini /Y
copy kszla_header.ini kszal_header.ini /Y
copy kszla_header.ini krend_header.ini /Y
copy kszla_header.ini kpfrm_header.ini /Y
copy kszla_header.ini knyug_header.ini /Y
copy kszla_header.ini karv_header.ini /Y
copy kszla_header.ini kajnl_header.ini /Y
copy kszla_header.ini bszla_header.ini /Y
copy kszla_header.ini bszal_header.ini /Y
copy kszla_header.ini brend_header.ini /Y
copy kszla_header.ini bpfrm_header.ini /Y
copy kszla_header.ini bnyug_header.ini /Y
copy kszla_header.ini bajnl_header.ini /Y
copy kszla_header.ini garlev_header.ini /Y
copy kszla_header.ini garvisz_header.ini /Y
copy kszla_header.ini garaki_header.ini /Y
copy kszla_header.ini garcs_header.ini /Y
copy kszla_header.ini garvki_header.ini /Y
copy kszla_header.ini garvbe_header.ini /Y
copy kszla_header.ini kisz_header.ini /Y
copy kszla_header_itemized.ini rki_header_itemized.ini /Y
copy kszla_header_itemized.ini rbe_header_itemized.ini /Y
copy kszla_header_itemized.ini lelt_header_itemized.ini /Y
copy kszla_header_itemized.ini kszal_header_itemized.ini /Y
copy kszla_header_itemized.ini krend_header_itemized.ini /Y
copy kszla_header_itemized.ini kpfrm_header_itemized.ini /Y
copy kszla_header_itemized.ini knyug_header_itemized.ini /Y
copy kszla_header_itemized.ini karv_header_itemized.ini /Y
copy kszla_header_itemized.ini kajnl_header_itemized.ini /Y
copy kszla_header_itemized.ini bszla_header_itemized.ini /Y
copy kszla_header_itemized.ini bszal_header_itemized.ini /Y
copy kszla_header_itemized.ini brend_header_itemized.ini /Y
copy kszla_header_itemized.ini bpfrm_header_itemized.ini /Y
copy kszla_header_itemized.ini bnyug_header_itemized.ini /Y
copy kszla_header_itemized.ini bajnl_header_itemized.ini /Y
copy kszla_header_itemized.ini garlev_header_itemized.ini /Y
copy kszla_header_itemized.ini garvisz_header_itemized.ini /Y
copy kszla_header_itemized.ini garaki_header_itemized.ini /Y
copy kszla_header_itemized.ini garcs_header_itemized.ini /Y
copy kszla_header_itemized.ini garvki_header_itemized.ini /Y
copy kszla_header_itemized.ini garvbe_header_itemized.ini /Y
copy kszla_header_itemized.ini kisz_header_itemized.ini /Y
